name: app_flutter
on:
  push:
    paths:
      - 'flutter_app/**'
      - '.github/workflows/app_flutter.yml'
  pull_request:
    paths:
      - 'flutter_app/**'
      - '.github/workflows/app_flutter.yml'
jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - working-directory: flutter_app
        run: flutter config --enable-web
      - working-directory: flutter_app
        run: flutter pub get
      - working-directory: flutter_app
        run: flutter analyze
      - working-directory: flutter_app
        run: flutter test || true
      - working-directory: flutter_app
        run: flutter build web --release
